/* The following code was generated by JFlex 1.7.0 tweaked for IntelliJ platform */

package org.jetbrains.kotlin.lexer;

import java.util.*;
import com.intellij.lexer.*;
import com.intellij.psi.*;
import com.intellij.psi.tree.IElementType;
import com.intellij.util.containers.Stack;
import org.jetbrains.kotlin.lexer.KotlinLexerException;
import org.jetbrains.kotlin.lexer.KtTokens;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>/home/redrield/IdeaProjects/Kotlin/compiler/psi/src/org/jetbrains/kotlin/lexer/Kotlin.flex</tt>
 */
class _JetLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int RAW_STRING = 4;
  public static final int SHORT_TEMPLATE_ENTRY = 6;
  public static final int BLOCK_COMMENT = 8;
  public static final int DOC_COMMENT = 10;
  public static final int LONG_TEMPLATE_ENTRY = 12;
  public static final int UNMATCHED_BACKTICK = 14;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  4,  4,  5,  5,  0, 0
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [11, 6, 4]
   * Total runtime size is 14336 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[(ZZ_CMAP_Z[ch>>10]<<6)|((ch>>4)&0x3f)]<<4)|(ch&0xf)];
  }

  /* The ZZ_CMAP_Z table has 1088 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7\1\10\2\11\1\12\1\13\6\14\1\15\23\14\1\16"+
    "\1\14\1\17\1\20\12\14\1\21\10\11\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1"+
    "\32\1\33\1\34\1\35\2\11\1\14\1\36\3\11\1\37\10\11\1\40\1\41\5\14\1\42\1\43"+
    "\11\11\1\44\2\11\1\45\5\11\1\46\4\11\1\47\1\50\4\11\51\14\1\51\3\14\1\52\1"+
    "\53\4\14\1\54\12\11\1\55\u0381\11");

  /* The ZZ_CMAP_Y table has 2944 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\1\1\11\1\12\1\13\1\14\1\13\1\14\34"+
    "\13\1\15\1\16\1\17\10\1\1\20\1\21\1\13\1\22\4\13\1\23\10\13\1\24\12\13\1\25"+
    "\1\13\1\26\1\25\1\13\1\27\4\1\1\13\1\30\1\31\2\1\2\13\1\30\1\1\1\32\1\25\5"+
    "\13\1\33\1\34\1\35\1\1\1\36\1\13\1\1\1\37\5\13\1\40\1\41\1\42\1\13\1\30\1"+
    "\43\1\13\1\44\1\45\1\1\1\13\1\46\4\1\1\13\1\47\4\1\1\50\2\13\1\51\1\1\1\52"+
    "\1\53\1\25\1\54\1\55\1\56\1\57\1\60\1\61\1\53\1\16\1\62\1\55\1\56\1\63\1\1"+
    "\1\64\1\65\1\66\1\67\1\22\1\56\1\70\1\1\1\71\1\53\1\72\1\73\1\55\1\56\1\70"+
    "\1\1\1\61\1\53\1\41\1\74\1\75\1\76\1\77\1\1\1\71\1\65\1\1\1\100\1\36\1\56"+
    "\1\51\1\1\1\101\1\53\1\1\1\102\1\36\1\56\1\103\1\1\1\60\1\53\1\104\1\100\1"+
    "\36\1\13\1\105\1\60\1\106\1\53\1\107\1\110\1\111\1\13\1\112\1\113\1\1\1\65"+
    "\1\1\1\25\2\13\1\114\1\113\1\115\2\1\1\116\1\117\1\120\1\121\1\122\1\123\2"+
    "\1\1\71\1\1\1\115\1\1\1\124\1\13\1\125\1\1\1\126\7\1\2\13\1\30\1\127\1\115"+
    "\1\130\1\131\1\132\1\133\1\115\2\13\1\134\2\13\1\135\24\13\1\136\1\137\2\13"+
    "\1\136\2\13\1\140\1\141\1\14\3\13\1\141\3\13\1\30\2\1\1\13\1\1\5\13\1\142"+
    "\1\25\45\13\1\143\1\13\1\25\1\30\4\13\1\30\1\144\1\145\1\16\1\13\1\16\1\13"+
    "\1\16\1\145\1\71\3\13\1\146\1\1\1\147\1\115\2\1\1\115\5\13\1\27\1\150\1\13"+
    "\1\151\4\13\1\40\1\13\1\152\2\1\1\65\1\13\1\153\1\154\2\13\1\155\1\13\1\77"+
    "\1\115\2\1\1\13\1\113\3\13\1\154\2\1\2\115\1\156\5\1\1\110\2\13\1\146\1\157"+
    "\1\115\2\1\1\160\1\13\1\161\1\42\2\13\1\40\1\1\2\13\1\146\1\1\1\162\1\42\1"+
    "\13\1\153\1\46\5\1\1\163\1\164\14\13\4\1\21\13\1\142\2\13\1\142\1\165\1\13"+
    "\1\153\3\13\1\166\1\167\1\170\1\125\1\167\2\1\1\171\4\1\1\172\1\1\1\125\6"+
    "\1\1\173\1\174\1\175\1\176\1\177\3\1\1\200\147\1\2\13\1\152\2\13\1\152\10"+
    "\13\1\201\1\202\2\13\1\134\3\13\1\203\1\1\1\13\1\113\4\204\4\1\1\127\35\1"+
    "\1\205\2\1\1\206\1\25\4\13\1\207\1\25\4\13\1\135\1\110\1\13\1\153\1\25\4\13"+
    "\1\152\1\1\1\13\1\30\3\1\1\13\40\1\133\13\1\40\4\1\135\13\1\40\2\1\10\13\1"+
    "\125\4\1\2\13\1\153\20\13\1\125\1\13\1\210\1\1\2\13\1\152\1\127\1\13\1\153"+
    "\4\13\1\40\2\1\1\211\1\212\5\13\1\213\1\13\1\152\1\27\3\1\1\211\1\214\1\13"+
    "\1\31\1\1\3\13\1\146\1\212\2\13\1\146\1\1\1\115\1\1\1\215\1\42\1\13\1\40\1"+
    "\13\1\113\1\1\1\13\1\125\1\50\2\13\1\31\1\127\1\115\1\216\1\217\2\13\1\46"+
    "\1\1\1\220\1\115\1\13\1\221\3\13\1\222\1\223\1\224\1\30\1\66\1\225\1\226\1"+
    "\204\2\13\1\135\1\40\7\13\1\31\1\115\72\13\1\146\1\13\1\227\2\13\1\155\20"+
    "\1\26\13\1\153\6\13\1\77\2\1\1\113\1\230\1\56\1\231\1\232\6\13\1\16\1\1\1"+
    "\160\25\13\1\153\1\1\4\13\1\212\2\13\1\27\2\1\1\155\7\1\1\216\7\13\1\125\1"+
    "\1\1\115\1\25\1\30\1\25\1\30\1\233\4\13\1\152\1\234\1\235\2\1\1\236\1\13\1"+
    "\14\1\237\2\153\2\1\7\13\1\30\30\1\1\13\1\125\3\13\1\71\2\1\2\13\1\1\1\13"+
    "\1\240\2\13\1\40\1\13\1\153\2\13\1\241\3\1\11\13\1\153\1\115\2\13\1\241\1"+
    "\13\1\155\2\13\1\27\3\13\1\146\11\1\23\13\1\113\1\13\1\40\1\27\11\1\1\242"+
    "\2\13\1\243\1\13\1\40\1\13\1\113\1\13\1\152\4\1\1\13\1\244\1\13\1\40\1\13"+
    "\1\77\4\1\3\13\1\245\4\1\1\71\1\246\1\13\1\146\2\1\1\13\1\125\1\13\1\125\2"+
    "\1\1\124\1\13\1\154\1\1\3\13\1\40\1\13\1\40\1\13\1\31\1\13\1\16\6\1\4\13\1"+
    "\46\3\1\3\13\1\31\3\13\1\31\60\1\1\160\2\13\1\27\2\1\1\65\1\1\1\160\2\13\2"+
    "\1\1\13\1\46\1\115\1\160\1\13\1\113\1\65\1\1\2\13\1\247\1\160\2\13\1\31\1"+
    "\250\1\251\2\1\1\13\1\22\1\155\5\1\1\252\1\253\1\46\2\13\1\152\1\1\1\115\1"+
    "\73\1\55\1\56\1\70\1\1\1\254\1\16\11\1\3\13\1\154\1\255\1\115\2\1\3\13\1\1"+
    "\1\256\1\115\12\1\2\13\1\152\2\1\1\257\2\1\3\13\1\1\1\260\1\115\2\1\2\13\1"+
    "\30\1\1\1\115\3\1\1\13\1\77\1\1\1\115\26\1\4\13\1\115\1\127\34\1\3\13\1\46"+
    "\20\1\1\56\1\13\1\152\1\1\1\71\1\115\1\1\1\212\1\13\67\1\71\13\1\77\16\1\14"+
    "\13\1\146\53\1\2\13\1\152\75\1\44\13\1\113\33\1\43\13\1\46\1\13\1\152\1\115"+
    "\6\1\1\13\1\153\1\1\3\13\1\1\1\146\1\115\1\160\1\261\1\13\67\1\4\13\1\154"+
    "\1\71\3\1\1\160\4\1\1\71\1\1\76\13\1\125\1\1\57\13\1\31\20\1\1\16\77\1\6\13"+
    "\1\30\1\125\1\46\1\77\66\1\5\13\1\216\3\13\1\145\1\262\1\263\1\264\3\13\1"+
    "\265\1\266\1\13\1\267\1\270\1\36\24\13\1\271\1\13\1\36\1\135\1\13\1\135\1"+
    "\13\1\216\1\13\1\216\1\152\1\13\1\152\1\13\1\56\1\13\1\56\1\13\1\272\3\273"+
    "\14\13\1\154\3\1\4\13\1\146\1\115\112\1\1\264\1\13\1\274\1\275\1\276\1\277"+
    "\1\300\1\301\1\302\1\155\1\303\1\155\24\1\55\13\1\113\2\1\103\13\1\154\15"+
    "\13\1\153\150\13\1\16\25\1\41\13\1\153\36\1");

  /* The ZZ_CMAP_A table has 3136 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\0\1\4\1\10\1\41\1\42\1\41\22\0\1\4\1\14\1\31\1\13\1\11\1\74\1\71\1\26"+
    "\1\100\1\101\1\40\1\66\1\104\1\25\1\22\1\12\1\15\11\1\1\75\1\103\1\67\1\64"+
    "\1\70\1\65\1\105\1\3\1\17\2\3\1\24\1\23\5\5\1\20\10\5\1\21\2\5\1\16\2\5\1"+
    "\76\1\27\1\77\1\73\1\2\1\7\1\46\1\57\1\53\1\63\1\45\1\52\1\56\1\34\1\35\1"+
    "\60\1\55\1\47\1\5\1\50\1\54\1\44\1\5\1\51\1\36\1\33\1\30\1\62\1\61\1\16\1"+
    "\43\1\5\1\32\1\72\1\37\1\102\6\0\1\41\24\0\1\5\12\0\1\5\4\0\1\5\5\0\27\5\1"+
    "\0\12\5\4\0\14\5\16\0\5\5\7\0\1\5\1\0\1\5\1\0\5\5\1\0\2\5\2\0\4\5\1\0\1\5"+
    "\6\0\1\5\1\0\3\5\1\0\1\5\1\0\4\5\1\0\23\5\1\0\13\5\10\0\6\5\1\0\26\5\2\0\1"+
    "\5\6\0\10\5\10\0\13\5\5\0\3\5\15\0\12\6\4\0\6\5\1\0\1\5\17\0\2\5\7\0\2\5\12"+
    "\6\3\5\2\0\2\5\1\0\16\5\15\0\11\5\13\0\1\5\16\0\12\6\6\5\4\0\2\5\4\0\1\5\5"+
    "\0\6\5\4\0\1\5\11\0\1\5\3\0\1\5\7\0\11\5\7\0\5\5\1\0\10\5\6\0\26\5\3\0\1\5"+
    "\2\0\1\5\7\0\12\5\4\0\12\6\1\5\4\0\10\5\2\0\2\5\2\0\26\5\1\0\7\5\1\0\1\5\3"+
    "\0\4\5\3\0\1\5\20\0\1\5\15\0\2\5\1\0\1\5\5\0\6\5\4\0\2\5\1\0\2\5\1\0\2\5\1"+
    "\0\2\5\17\0\4\5\1\0\1\5\7\0\12\6\2\0\3\5\20\0\11\5\1\0\2\5\1\0\2\5\1\0\5\5"+
    "\3\0\1\5\2\0\1\5\30\0\1\5\13\0\10\5\2\0\1\5\3\0\1\5\1\0\6\5\3\0\3\5\1\0\4"+
    "\5\3\0\2\5\1\0\1\5\1\0\2\5\3\0\2\5\3\0\3\5\3\0\14\5\13\0\10\5\1\0\2\5\10\0"+
    "\3\5\5\0\1\5\4\0\10\5\1\0\6\5\1\0\5\5\3\0\1\5\3\0\2\5\15\0\13\5\2\0\1\5\6"+
    "\0\3\5\10\0\1\5\12\0\6\5\5\0\22\5\3\0\10\5\1\0\11\5\1\0\1\5\2\0\7\5\11\0\1"+
    "\5\1\0\2\5\14\0\12\6\7\0\2\5\1\0\1\5\2\0\2\5\1\0\1\5\2\0\1\5\6\0\4\5\1\0\7"+
    "\5\1\0\3\5\1\0\1\5\1\0\1\5\2\0\2\5\1\0\4\5\1\0\2\5\11\0\1\5\2\0\5\5\1\0\1"+
    "\5\11\0\12\6\2\0\14\5\1\0\24\5\13\0\5\5\22\0\7\5\4\0\4\5\3\0\1\5\3\0\2\5\7"+
    "\0\3\5\4\0\15\5\14\0\1\5\1\0\6\5\1\0\1\5\5\0\1\5\2\0\13\5\1\0\15\5\1\0\4\5"+
    "\2\0\7\5\1\0\1\5\1\0\4\5\2\0\1\5\1\0\4\5\2\0\7\5\1\0\1\5\1\0\4\5\2\0\16\5"+
    "\2\0\6\5\2\0\15\5\2\0\1\5\1\0\10\5\7\0\15\5\1\0\6\5\23\0\1\5\4\0\1\5\3\0\5"+
    "\5\2\0\22\5\1\0\1\5\5\0\17\5\1\0\16\5\2\0\5\5\13\0\14\5\13\0\1\5\15\0\7\5"+
    "\7\0\16\5\15\0\2\5\12\6\3\0\3\5\11\0\4\5\1\0\4\5\3\0\2\5\11\0\10\5\1\0\1\5"+
    "\1\0\1\5\1\0\1\5\1\0\6\5\1\0\7\5\1\0\1\5\3\0\3\5\1\0\7\5\3\0\4\5\2\0\6\5\14"+
    "\0\2\41\7\0\1\5\15\0\1\5\2\0\1\5\4\0\1\5\2\0\12\5\1\0\1\5\3\0\5\5\6\0\1\5"+
    "\1\0\1\5\1\0\1\5\1\0\4\5\1\0\13\5\2\0\4\5\5\0\5\5\4\0\1\5\4\0\2\5\13\0\5\5"+
    "\6\0\4\5\3\0\2\5\14\0\10\5\7\0\10\5\1\0\7\5\6\0\2\5\12\0\5\5\5\0\2\5\3\0\7"+
    "\5\6\0\3\5\12\6\2\5\13\0\11\5\2\0\27\5\2\0\7\5\1\0\3\5\1\0\4\5\1\0\4\5\2\0"+
    "\6\5\3\0\1\5\1\0\1\5\2\0\5\5\1\0\12\5\12\6\5\5\1\0\3\5\1\0\10\5\4\0\7\5\3"+
    "\0\1\5\3\0\2\5\1\0\1\5\3\0\2\5\2\0\5\5\2\0\1\5\1\0\1\5\30\0\3\5\3\0\6\5\2"+
    "\0\6\5\2\0\6\5\11\0\7\5\4\0\5\5\3\0\5\5\5\0\1\5\1\0\10\5\1\0\5\5\1\0\1\5\1"+
    "\0\2\5\1\0\2\5\1\0\12\5\6\0\12\5\2\0\6\5\2\0\6\5\2\0\6\5\2\0\3\5\3\0\14\5"+
    "\1\0\16\5\1\0\2\5\1\0\2\5\1\0\10\5\6\0\4\5\4\0\16\5\2\0\1\5\1\0\14\5\1\0\2"+
    "\5\3\0\1\5\2\0\4\5\1\0\2\5\12\0\10\5\6\0\6\5\1\0\3\5\1\0\12\5\3\0\1\5\12\0"+
    "\4\5\13\0\12\6\1\5\1\0\1\5\3\0\7\5\1\0\1\5\1\0\4\5\1\0\17\5\1\0\2\5\14\0\3"+
    "\5\7\0\4\5\11\0\2\5\1\0\1\5\20\0\4\5\10\0\1\5\13\0\10\5\5\0\3\5\2\0\1\5\2"+
    "\0\2\5\2\0\4\5\1\0\14\5\1\0\1\5\1\0\7\5\1\0\21\5\1\0\4\5\2\0\10\5\1\0\7\5"+
    "\1\0\14\5\1\0\4\5\1\0\5\5\1\0\1\5\3\0\14\5\2\0\13\5\1\0\10\5\2\0\22\6\1\0"+
    "\2\5\1\0\1\5\2\0\1\5\1\0\12\5\1\0\4\5\1\0\1\5\1\0\1\5\6\0\1\5\4\0\1\5\1\0"+
    "\1\5\1\0\1\5\1\0\3\5\1\0\2\5\1\0\1\5\2\0\1\5\1\0\1\5\1\0\1\5\1\0\1\5\1\0\1"+
    "\5\1\0\2\5\1\0\1\5\2\0\4\5\1\0\7\5\1\0\4\5\1\0\4\5\1\0\1\5\1\0\12\5\1\0\5"+
    "\5\1\0\3\5\1\0\5\5\1\0\5\5");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\6\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\1\10\1\2\1\11\1\12\1\13\1\14\1\15"+
    "\3\3\1\16\1\17\14\3\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\42\1\1\1\44\2\42\1\45\1\1\1\45\3\46"+
    "\1\47\1\50\2\2\1\0\2\51\1\0\1\52\1\0"+
    "\1\53\1\54\1\55\1\56\1\0\1\57\1\0\2\2"+
    "\1\51\1\60\1\61\1\62\1\63\2\13\1\0\3\3"+
    "\1\64\1\65\1\66\1\3\1\67\2\3\1\70\13\3"+
    "\1\71\1\72\1\73\1\74\1\75\1\76\1\77\1\100"+
    "\1\101\1\102\1\103\1\104\1\105\1\106\1\107\1\110"+
    "\1\111\1\112\1\0\1\113\2\114\2\0\1\45\1\115"+
    "\1\116\1\0\1\117\1\51\1\3\1\0\1\120\1\121"+
    "\1\122\1\123\1\0\1\124\1\125\4\3\1\126\4\3"+
    "\1\127\2\3\1\130\1\3\1\131\6\3\1\132\1\133"+
    "\1\134\1\135\1\136\1\137\2\0\1\140\2\45\1\52"+
    "\1\141\1\142\1\143\2\3\1\144\3\3\1\145\1\146"+
    "\7\3\1\147\1\150\1\112\1\0\1\151\1\152\3\3"+
    "\1\153\2\3\1\154\1\155\2\3\1\156\1\157\1\0"+
    "\1\3\1\160\2\3\1\161\1\3\1\162\2\3\1\163"+
    "\3\3\1\164\1\165\1\166";

  private static int [] zzUnpackAction() {
    int [] result = new int[243];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\106\0\214\0\322\0\u0118\0\u015e\0\u01a4\0\u01ea"+
    "\0\u0230\0\u0276\0\u02bc\0\u0302\0\u0348\0\u038e\0\u03d4\0\u041a"+
    "\0\u0460\0\u04a6\0\u04ec\0\u0532\0\u01a4\0\u0578\0\u05be\0\u0604"+
    "\0\u01a4\0\u064a\0\u0690\0\u06d6\0\u071c\0\u0762\0\u07a8\0\u07ee"+
    "\0\u0834\0\u087a\0\u08c0\0\u0906\0\u094c\0\u0992\0\u09d8\0\u01a4"+
    "\0\u0a1e\0\u0a64\0\u0aaa\0\u0af0\0\u0b36\0\u0b7c\0\u0bc2\0\u0c08"+
    "\0\u01a4\0\u01a4\0\u01a4\0\u01a4\0\u01a4\0\u0c4e\0\u01a4\0\u01a4"+
    "\0\u0c94\0\u01a4\0\u0cda\0\u0d20\0\u01a4\0\u01a4\0\u0d66\0\u0dac"+
    "\0\u0df2\0\u0e38\0\u01a4\0\u0e7e\0\u0ec4\0\u01a4\0\u01a4\0\u0f0a"+
    "\0\u0f50\0\u0f96\0\u01a4\0\u0fdc\0\u1022\0\u1068\0\u10ae\0\u10f4"+
    "\0\u113a\0\u01a4\0\u1180\0\u11c6\0\u120c\0\u1252\0\u1298\0\u12de"+
    "\0\u1324\0\u136a\0\u01a4\0\u01a4\0\u01a4\0\u01a4\0\u13b0\0\u13f6"+
    "\0\u143c\0\u1482\0\u14c8\0\u0230\0\u150e\0\u0230\0\u1554\0\u01a4"+
    "\0\u159a\0\u15e0\0\u1626\0\u166c\0\u16b2\0\u16f8\0\u173e\0\u1784"+
    "\0\u17ca\0\u1810\0\u1856\0\u189c\0\u18e2\0\u1928\0\u0230\0\u196e"+
    "\0\u01a4\0\u01a4\0\u01a4\0\u01a4\0\u19b4\0\u01a4\0\u19fa\0\u01a4"+
    "\0\u01a4\0\u01a4\0\u01a4\0\u01a4\0\u01a4\0\u01a4\0\u01a4\0\u1a40"+
    "\0\u1a86\0\u01a4\0\u01a4\0\u1acc\0\u1b12\0\u1b58\0\u1b9e\0\u01a4"+
    "\0\u01a4\0\u1be4\0\u01a4\0\u1c2a\0\u01a4\0\u1c70\0\u1cb6\0\u1cfc"+
    "\0\u1cfc\0\u01a4\0\u1d42\0\u01a4\0\u01a4\0\u1d88\0\u1dce\0\u1e14"+
    "\0\u1e5a\0\u0230\0\u1ea0\0\u1ee6\0\u1f2c\0\u1f72\0\u01a4\0\u1fb8"+
    "\0\u1ffe\0\u0230\0\u2044\0\u0230\0\u208a\0\u20d0\0\u2116\0\u215c"+
    "\0\u21a2\0\u21e8\0\u0230\0\u0230\0\u01a4\0\u01a4\0\u01a4\0\u222e"+
    "\0\u2274\0\u22ba\0\u1b12\0\u01a4\0\u2300\0\u01a4\0\u01a4\0\u01a4"+
    "\0\u0230\0\u2346\0\u238c\0\u0230\0\u23d2\0\u2418\0\u245e\0\u0230"+
    "\0\u0230\0\u24a4\0\u24ea\0\u2530\0\u2576\0\u25bc\0\u2602\0\u2648"+
    "\0\u0230\0\u01a4\0\u01a4\0\u268e\0\u0dac\0\u0230\0\u26d4\0\u271a"+
    "\0\u2760\0\u0230\0\u27a6\0\u27ec\0\u0230\0\u0230\0\u2832\0\u2878"+
    "\0\u0230\0\u0230\0\u28be\0\u2904\0\u0230\0\u294a\0\u2990\0\u0230"+
    "\0\u29d6\0\u0230\0\u2a1c\0\u2a62\0\u0230\0\u2aa8\0\u2aee\0\u2b34"+
    "\0\u0230\0\u0230\0\u0230";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[243];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\1\10\2\11\1\12\1\11\1\7\1\13\1\12"+
    "\1\14\1\15\1\16\1\17\1\20\4\11\1\21\2\11"+
    "\1\22\1\23\1\7\1\11\1\24\1\25\1\26\1\11"+
    "\1\27\1\30\1\31\1\32\1\0\1\12\1\11\1\33"+
    "\1\34\1\35\1\11\1\36\1\37\1\40\1\41\1\42"+
    "\2\11\1\43\1\11\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\1\65\1\66\1\67\1\70"+
    "\10\71\1\72\1\73\15\71\1\74\1\71\1\75\64\71"+
    "\1\76\1\73\15\71\1\76\1\71\1\77\54\71\2\7"+
    "\2\100\1\7\1\100\1\7\1\101\1\0\5\7\4\100"+
    "\1\7\2\100\3\7\1\100\2\7\1\102\3\100\2\7"+
    "\2\0\21\100\22\7\12\103\1\104\25\103\1\105\1\0"+
    "\44\103\1\7\1\10\2\11\1\12\1\11\1\7\1\13"+
    "\1\12\1\14\1\15\1\16\1\17\1\20\4\11\1\21"+
    "\2\11\1\22\1\23\1\7\1\11\1\24\1\106\1\26"+
    "\1\11\1\27\1\30\1\107\1\32\1\0\1\12\1\11"+
    "\1\33\1\34\1\35\1\11\1\36\1\37\1\40\1\41"+
    "\1\42\2\11\1\43\1\11\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\57"+
    "\1\60\1\61\1\62\1\63\1\64\1\65\1\66\1\67"+
    "\1\70\107\0\2\10\12\0\1\10\2\0\1\110\1\111"+
    "\1\112\1\113\1\114\3\0\1\111\14\0\1\114\1\0"+
    "\1\110\2\0\1\113\34\0\3\11\1\0\2\11\6\0"+
    "\5\11\1\0\2\11\3\0\1\11\2\0\4\11\4\0"+
    "\21\11\26\0\1\12\3\0\1\12\31\0\1\12\43\0"+
    "\7\115\2\0\75\115\2\0\2\116\1\0\1\116\1\0"+
    "\1\117\6\0\4\116\1\0\2\116\3\0\1\116\2\0"+
    "\4\116\4\0\21\116\34\0\1\120\25\0\1\121\23\0"+
    "\1\122\35\0\1\123\126\0\1\124\26\0\1\125\22\0"+
    "\2\126\12\0\1\126\1\127\1\130\1\110\1\111\1\112"+
    "\1\113\1\114\3\0\1\111\14\0\1\114\1\0\1\110"+
    "\2\0\1\113\4\0\1\130\27\0\1\131\13\0\1\131"+
    "\4\0\1\132\110\0\1\133\36\0\1\134\3\0\1\135"+
    "\15\0\10\23\1\0\15\23\1\136\1\137\56\23\31\0"+
    "\1\140\55\0\3\11\1\0\2\11\6\0\5\11\1\0"+
    "\2\11\3\0\1\11\2\0\1\11\1\141\2\11\4\0"+
    "\1\142\5\11\1\143\12\11\23\0\3\11\1\0\2\11"+
    "\6\0\5\11\1\0\2\11\3\0\1\11\2\0\3\11"+
    "\1\144\4\0\5\11\1\145\1\11\1\146\11\11\23\0"+
    "\3\11\1\0\2\11\6\0\5\11\1\0\2\11\3\0"+
    "\1\147\2\0\4\11\4\0\21\11\106\0\1\150\22\0"+
    "\3\11\1\0\2\11\6\0\5\11\1\0\2\11\3\0"+
    "\1\11\2\0\4\11\4\0\3\11\1\151\15\11\23\0"+
    "\3\11\1\0\2\11\6\0\5\11\1\0\2\11\3\0"+
    "\1\11\2\0\4\11\4\0\4\11\1\152\14\11\23\0"+
    "\3\11\1\0\2\11\6\0\5\11\1\0\2\11\3\0"+
    "\1\11\2\0\3\11\1\153\4\0\21\11\23\0\3\11"+
    "\1\0\2\11\6\0\5\11\1\0\2\11\3\0\1\154"+
    "\2\0\4\11\4\0\21\11\23\0\3\11\1\0\2\11"+
    "\6\0\5\11\1\0\2\11\3\0\1\11\2\0\4\11"+
    "\4\0\2\11\1\155\16\11\23\0\3\11\1\0\2\11"+
    "\6\0\5\11\1\0\2\11\3\0\1\156\2\0\4\11"+
    "\4\0\3\11\1\157\5\11\1\160\7\11\23\0\3\11"+
    "\1\0\2\11\6\0\5\11\1\0\2\11\3\0\1\11"+
    "\2\0\4\11\4\0\4\11\1\161\4\11\1\162\7\11"+
    "\23\0\3\11\1\0\2\11\6\0\5\11\1\0\2\11"+
    "\3\0\1\11\2\0\4\11\4\0\14\11\1\163\4\11"+
    "\23\0\3\11\1\0\2\11\6\0\5\11\1\0\2\11"+
    "\3\0\1\11\2\0\4\11\4\0\6\11\1\164\12\11"+
    "\23\0\3\11\1\0\2\11\6\0\5\11\1\0\2\11"+
    "\3\0\1\11\2\0\1\11\1\165\2\11\4\0\21\11"+
    "\23\0\3\11\1\0\2\11\6\0\5\11\1\0\2\11"+
    "\3\0\1\11\2\0\4\11\4\0\3\11\1\166\15\11"+
    "\23\0\3\11\1\0\2\11\6\0\5\11\1\0\2\11"+
    "\3\0\1\11\2\0\4\11\4\0\11\11\1\167\7\11"+
    "\106\0\1\170\3\0\1\171\101\0\1\172\1\0\1\173"+
    "\103\0\1\174\2\0\1\175\102\0\1\176\3\0\1\177"+
    "\101\0\1\200\4\0\1\201\100\0\1\202\5\0\1\203"+
    "\77\0\1\204\105\0\1\205\116\0\1\206\113\0\1\207"+
    "\2\0\10\71\2\0\15\71\1\0\1\71\1\0\54\71"+
    "\2\0\2\210\1\0\1\210\1\0\1\211\6\0\4\210"+
    "\1\0\2\210\3\0\1\210\1\0\1\212\4\210\4\0"+
    "\21\210\22\0\10\213\1\0\17\213\1\214\55\213\31\0"+
    "\1\215\55\0\3\100\1\0\2\100\6\0\5\100\1\0"+
    "\2\100\3\0\1\100\2\0\4\100\4\0\21\100\22\0"+
    "\7\216\2\0\75\216\1\0\3\100\1\0\2\100\6\0"+
    "\5\100\1\0\2\100\3\0\1\100\2\0\1\100\1\217"+
    "\2\100\4\0\21\100\62\0\1\220\57\0\1\221\115\0"+
    "\1\222\103\0\1\110\1\0\1\222\24\0\1\110\37\0"+
    "\1\131\13\0\1\131\4\0\1\223\64\0\2\224\12\0"+
    "\1\224\5\0\1\113\1\0\1\224\24\0\1\113\13\0"+
    "\1\224\17\0\7\115\1\225\1\0\75\115\1\0\3\116"+
    "\1\0\2\116\6\0\5\116\1\0\2\116\3\0\1\116"+
    "\2\0\4\116\4\0\21\116\22\0\7\226\2\0\75\226"+
    "\10\120\1\0\75\120\40\0\1\227\45\0\10\123\1\0"+
    "\75\123\36\0\1\230\11\0\1\231\121\0\1\232\22\0"+
    "\2\126\12\0\1\126\4\0\1\233\1\113\1\114\20\0"+
    "\1\114\4\0\1\113\34\0\3\127\11\0\1\127\1\0"+
    "\1\127\1\110\1\111\1\222\2\127\3\0\1\111\14\0"+
    "\2\127\1\110\2\0\2\127\3\0\1\127\3\0\1\127"+
    "\23\0\2\130\12\0\1\130\2\0\1\110\1\111\1\222"+
    "\5\0\1\111\16\0\1\110\37\0\2\131\12\0\1\131"+
    "\5\0\1\113\1\114\20\0\1\114\4\0\1\113\55\0"+
    "\1\234\63\0\10\23\1\0\75\23\31\0\1\235\55\0"+
    "\3\11\1\0\2\11\6\0\5\11\1\0\2\11\3\0"+
    "\1\11\2\0\2\11\1\236\1\11\4\0\6\11\1\237"+
    "\12\11\23\0\3\11\1\0\2\11\6\0\5\11\1\0"+
    "\2\11\3\0\1\11\2\0\4\11\4\0\1\11\1\240"+
    "\17\11\23\0\3\11\1\0\2\11\6\0\5\11\1\0"+
    "\2\11\3\0\1\241\2\0\4\11\4\0\1\242\20\11"+
    "\23\0\3\11\1\0\2\11\6\0\5\11\1\0\2\11"+
    "\3\0\1\11\2\0\1\243\3\11\4\0\21\11\23\0"+
    "\3\11\1\0\2\11\6\0\5\11\1\0\2\11\3\0"+
    "\1\11\2\0\4\11\4\0\1\11\1\244\17\11\23\0"+
    "\3\11\1\0\2\11\6\0\5\11\1\0\2\11\3\0"+
    "\1\11\2\0\4\11\4\0\10\11\1\245\10\11\23\0"+
    "\3\11\1\0\2\11\6\0\5\11\1\0\2\11\3\0"+
    "\1\11\2\0\3\11\1\246\4\0\21\11\23\0\3\11"+
    "\1\0\2\11\6\0\5\11\1\0\2\11\3\0\1\11"+
    "\2\0\4\11\4\0\21\11\1\0\1\247\21\0\3\11"+
    "\1\0\2\11\6\0\5\11\1\0\2\11\3\0\1\11"+
    "\2\0\4\11\4\0\4\11\1\250\14\11\23\0\3\11"+
    "\1\0\2\11\6\0\5\11\1\0\2\11\3\0\1\11"+
    "\2\0\1\251\3\11\4\0\21\11\23\0\3\11\1\0"+
    "\2\11\6\0\5\11\1\0\2\11\3\0\1\11\2\0"+
    "\4\11\4\0\5\11\1\252\13\11\23\0\3\11\1\0"+
    "\2\11\6\0\5\11\1\0\2\11\3\0\1\11\2\0"+
    "\4\11\4\0\4\11\1\253\14\11\23\0\3\11\1\0"+
    "\2\11\6\0\5\11\1\0\2\11\3\0\1\11\2\0"+
    "\4\11\4\0\6\11\1\254\12\11\23\0\3\11\1\0"+
    "\2\11\6\0\5\11\1\0\2\11\3\0\1\11\2\0"+
    "\4\11\4\0\3\11\1\255\15\11\23\0\3\11\1\0"+
    "\2\11\6\0\5\11\1\0\2\11\3\0\1\11\2\0"+
    "\4\11\4\0\5\11\1\256\13\11\23\0\3\11\1\0"+
    "\2\11\6\0\5\11\1\0\2\11\3\0\1\11\2\0"+
    "\4\11\4\0\15\11\1\257\3\11\23\0\3\11\1\0"+
    "\2\11\6\0\5\11\1\0\2\11\3\0\1\11\2\0"+
    "\4\11\4\0\2\11\1\260\16\11\23\0\3\11\1\0"+
    "\2\11\6\0\5\11\1\0\2\11\3\0\1\11\2\0"+
    "\2\11\1\261\1\11\4\0\2\11\1\262\16\11\23\0"+
    "\3\11\1\0\2\11\6\0\5\11\1\0\2\11\3\0"+
    "\1\11\2\0\4\11\4\0\4\11\1\263\1\11\1\264"+
    "\12\11\106\0\1\265\105\0\1\266\105\0\1\267\3\0"+
    "\1\270\16\0\3\210\1\0\2\210\6\0\5\210\1\0"+
    "\2\210\3\0\1\210\2\0\4\210\4\0\21\210\22\0"+
    "\7\271\2\0\75\271\1\0\1\272\1\0\1\272\11\0"+
    "\1\272\1\0\1\272\3\0\2\272\20\0\2\272\3\0"+
    "\2\272\3\0\1\272\3\0\1\272\53\0\1\273\54\0"+
    "\7\216\1\274\1\0\75\216\1\0\3\100\1\0\2\100"+
    "\6\0\5\100\1\0\2\100\3\0\1\100\2\0\2\100"+
    "\1\275\1\100\4\0\21\100\44\0\1\223\64\0\2\224"+
    "\12\0\1\224\5\0\1\113\26\0\1\113\33\0\7\226"+
    "\1\276\1\0\75\226\12\0\1\277\74\0\3\300\1\0"+
    "\2\300\6\0\5\300\1\0\2\300\3\0\1\300\2\0"+
    "\4\300\4\0\21\300\23\0\1\131\13\0\1\131\71\0"+
    "\3\11\1\0\2\11\6\0\5\11\1\0\2\11\3\0"+
    "\1\11\2\0\3\11\1\301\4\0\21\11\23\0\3\11"+
    "\1\0\2\11\6\0\5\11\1\0\2\11\3\0\1\11"+
    "\2\0\4\11\4\0\11\11\1\302\7\11\23\0\3\11"+
    "\1\0\2\11\6\0\5\11\1\0\2\11\3\0\1\11"+
    "\2\0\4\11\4\0\2\11\1\303\16\11\23\0\3\11"+
    "\1\0\2\11\6\0\5\11\1\0\2\11\3\0\1\11"+
    "\2\0\4\11\4\0\2\11\1\304\16\11\23\0\3\11"+
    "\1\0\2\11\6\0\5\11\1\0\2\11\3\0\1\11"+
    "\2\0\4\11\4\0\2\11\1\305\16\11\23\0\3\11"+
    "\1\0\2\11\6\0\5\11\1\0\2\11\3\0\1\11"+
    "\2\0\4\11\4\0\2\11\1\306\16\11\23\0\3\11"+
    "\1\0\2\11\6\0\5\11\1\0\2\11\3\0\1\11"+
    "\2\0\4\11\4\0\12\11\1\307\6\11\23\0\3\11"+
    "\1\0\2\11\6\0\5\11\1\0\2\11\3\0\1\11"+
    "\2\0\4\11\4\0\2\11\1\310\16\11\23\0\3\11"+
    "\1\0\2\11\6\0\5\11\1\0\2\11\3\0\1\11"+
    "\2\0\4\11\4\0\4\11\1\311\14\11\23\0\3\11"+
    "\1\0\2\11\6\0\5\11\1\0\2\11\3\0\1\312"+
    "\2\0\4\11\4\0\21\11\23\0\3\11\1\0\2\11"+
    "\6\0\5\11\1\0\2\11\3\0\1\11\2\0\3\11"+
    "\1\313\4\0\21\11\23\0\3\11\1\0\2\11\6\0"+
    "\5\11\1\0\2\11\3\0\1\11\2\0\3\11\1\314"+
    "\4\0\21\11\23\0\3\11\1\0\2\11\6\0\5\11"+
    "\1\0\2\11\3\0\1\11\2\0\1\315\3\11\4\0"+
    "\21\11\23\0\3\11\1\0\2\11\6\0\5\11\1\0"+
    "\2\11\3\0\1\11\2\0\4\11\4\0\2\11\1\316"+
    "\16\11\23\0\3\11\1\0\2\11\6\0\5\11\1\0"+
    "\2\11\3\0\1\11\2\0\4\11\4\0\3\11\1\317"+
    "\15\11\23\0\3\11\1\0\2\11\6\0\5\11\1\0"+
    "\2\11\3\0\1\11\2\0\4\11\4\0\4\11\1\320"+
    "\14\11\23\0\3\11\1\0\2\11\6\0\5\11\1\0"+
    "\2\11\3\0\1\11\2\0\4\11\4\0\5\11\1\321"+
    "\13\11\106\0\1\322\21\0\7\271\1\323\1\0\75\271"+
    "\1\0\1\324\1\0\1\324\11\0\1\324\1\0\1\324"+
    "\3\0\2\324\20\0\2\324\3\0\2\324\3\0\1\324"+
    "\3\0\1\324\23\0\3\100\1\0\2\100\6\0\5\100"+
    "\1\0\2\100\3\0\1\100\2\0\3\100\1\325\4\0"+
    "\21\100\23\0\3\11\1\0\2\11\6\0\5\11\1\0"+
    "\2\11\3\0\1\11\2\0\4\11\4\0\16\11\1\326"+
    "\2\11\23\0\3\11\1\0\2\11\6\0\5\11\1\0"+
    "\2\11\3\0\1\11\2\0\4\11\4\0\3\11\1\327"+
    "\5\11\1\330\7\11\23\0\3\11\1\0\2\11\6\0"+
    "\5\11\1\0\2\11\3\0\1\11\2\0\4\11\4\0"+
    "\6\11\1\331\12\11\23\0\3\11\1\0\2\11\6\0"+
    "\5\11\1\0\2\11\3\0\1\11\2\0\4\11\4\0"+
    "\6\11\1\332\12\11\23\0\3\11\1\0\2\11\6\0"+
    "\5\11\1\0\2\11\3\0\1\11\2\0\4\11\4\0"+
    "\3\11\1\333\15\11\23\0\3\11\1\0\2\11\6\0"+
    "\5\11\1\0\2\11\3\0\1\11\2\0\4\11\4\0"+
    "\6\11\1\334\12\11\23\0\3\11\1\0\2\11\6\0"+
    "\5\11\1\0\2\11\3\0\1\11\2\0\4\11\4\0"+
    "\2\11\1\335\16\11\23\0\3\11\1\0\2\11\6\0"+
    "\5\11\1\0\2\11\3\0\1\11\2\0\3\11\1\336"+
    "\4\0\21\11\23\0\3\11\1\0\2\11\6\0\5\11"+
    "\1\0\2\11\3\0\1\11\2\0\2\11\1\337\1\11"+
    "\4\0\21\11\23\0\3\11\1\0\2\11\6\0\5\11"+
    "\1\0\2\11\3\0\1\11\2\0\4\11\4\0\10\11"+
    "\1\340\10\11\23\0\3\11\1\0\2\11\6\0\5\11"+
    "\1\0\2\11\3\0\1\11\2\0\4\11\4\0\12\11"+
    "\1\341\6\11\23\0\3\11\1\0\2\11\6\0\5\11"+
    "\1\0\2\11\3\0\1\11\2\0\4\11\4\0\2\11"+
    "\1\342\16\11\23\0\1\343\1\0\1\343\11\0\1\343"+
    "\1\0\1\343\3\0\2\343\20\0\2\343\3\0\2\343"+
    "\3\0\1\343\3\0\1\343\23\0\3\11\1\0\2\11"+
    "\6\0\5\11\1\0\2\11\3\0\1\11\2\0\4\11"+
    "\4\0\4\11\1\344\14\11\23\0\3\11\1\0\2\11"+
    "\6\0\5\11\1\0\2\11\3\0\1\11\2\0\4\11"+
    "\4\0\7\11\1\345\11\11\23\0\3\11\1\0\2\11"+
    "\6\0\5\11\1\0\2\11\3\0\1\11\2\0\4\11"+
    "\4\0\7\11\1\346\11\11\23\0\3\11\1\0\2\11"+
    "\6\0\5\11\1\0\2\11\3\0\1\11\2\0\4\11"+
    "\4\0\13\11\1\347\5\11\23\0\3\11\1\0\2\11"+
    "\6\0\5\11\1\0\2\11\3\0\1\11\2\0\4\11"+
    "\4\0\5\11\1\350\13\11\23\0\3\11\1\0\2\11"+
    "\6\0\5\11\1\0\2\11\3\0\1\11\2\0\4\11"+
    "\4\0\5\11\1\351\13\11\23\0\3\11\1\0\2\11"+
    "\6\0\5\11\1\0\2\11\3\0\1\11\2\0\1\352"+
    "\3\11\4\0\21\11\23\0\1\213\1\0\1\213\11\0"+
    "\1\213\1\0\1\213\3\0\2\213\20\0\2\213\3\0"+
    "\2\213\3\0\1\213\3\0\1\213\23\0\3\11\1\0"+
    "\2\11\6\0\5\11\1\0\2\11\3\0\1\11\2\0"+
    "\2\11\1\353\1\11\4\0\21\11\23\0\3\11\1\0"+
    "\2\11\6\0\5\11\1\0\2\11\3\0\1\11\2\0"+
    "\4\11\4\0\3\11\1\354\15\11\23\0\3\11\1\0"+
    "\2\11\6\0\5\11\1\0\2\11\3\0\1\11\2\0"+
    "\4\11\4\0\2\11\1\355\16\11\23\0\3\11\1\0"+
    "\2\11\6\0\5\11\1\0\2\11\3\0\1\356\2\0"+
    "\4\11\4\0\21\11\23\0\3\11\1\0\2\11\6\0"+
    "\5\11\1\0\2\11\3\0\1\11\2\0\4\11\4\0"+
    "\3\11\1\357\15\11\23\0\3\11\1\0\2\11\6\0"+
    "\5\11\1\0\2\11\3\0\1\11\2\0\4\11\4\0"+
    "\10\11\1\360\10\11\23\0\3\11\1\0\2\11\6\0"+
    "\5\11\1\0\2\11\3\0\1\11\2\0\4\11\4\0"+
    "\2\11\1\361\16\11\23\0\3\11\1\0\2\11\6\0"+
    "\5\11\1\0\2\11\3\0\1\11\2\0\3\11\1\362"+
    "\4\0\21\11\23\0\3\11\1\0\2\11\6\0\5\11"+
    "\1\0\2\11\3\0\1\11\2\0\4\11\4\0\2\11"+
    "\1\363\16\11\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11130];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\6\0\1\11\15\1\1\11\3\1\1\11\16\1\1\11"+
    "\10\1\5\11\1\1\2\11\1\1\1\11\2\1\2\11"+
    "\4\1\1\11\2\1\2\11\2\1\1\0\1\11\1\1"+
    "\1\0\1\1\1\0\2\1\1\11\1\1\1\0\1\1"+
    "\1\0\4\1\4\11\1\1\1\0\7\1\1\11\20\1"+
    "\4\11\1\1\1\11\1\1\10\11\1\1\1\0\2\11"+
    "\1\1\2\0\1\1\2\11\1\0\1\11\1\1\1\11"+
    "\1\0\3\1\1\11\1\0\2\11\11\1\1\11\15\1"+
    "\3\11\1\1\2\0\1\1\1\11\1\1\3\11\21\1"+
    "\2\11\1\0\16\1\1\0\20\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[243];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private static final class State {
        final int lBraceCount;
        final int ltCount;
        final int state;

        public State(int state, int lBraceCount, int ltCount) {
            this.state = state;
            this.lBraceCount = lBraceCount;
            this.ltCount = ltCount;
        }

        @Override
        public String toString() {
            return "yystate = " + state + (lBraceCount == 0 ? "" : "lBraceCount = " + lBraceCount);
        }
    }

    private final Stack<State> states = new Stack<State>();
    private int lBraceCount;
    private int ltCount;

    private int commentStart;
    private int commentDepth;

    private void pushState(int state) {
        states.push(new State(yystate(), lBraceCount, ltCount));
        lBraceCount = 0;
        ltCount = 0;
        yybegin(state);
    }

    private void popState() {
        State state = states.pop();
        lBraceCount = state.lBraceCount;
        ltCount = state.ltCount;
        yybegin(state.state);
    }

    private IElementType commentStateToTokenType(int state) {
        switch (state) {
            case BLOCK_COMMENT:
                return KtTokens.BLOCK_COMMENT;
            case DOC_COMMENT:
                return KtTokens.DOC_COMMENT;
            default:
                throw new IllegalArgumentException("Unexpected state: " + state);
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  _JetLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) throws KotlinLexerException {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new KotlinLexerException(message + "\n at '" + yytext() + "'\n" + zzBuffer);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  throws KotlinLexerException {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
      return;

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException, KotlinLexerException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        zzDoEOF();
        switch (zzLexicalState) {
            case BLOCK_COMMENT: {
              int state = yystate();
        popState();
        zzStartRead = commentStart;
        return commentStateToTokenType(state);
            }  // fall though
            case 244: break;
            case DOC_COMMENT: {
              int state = yystate();
        popState();
        zzStartRead = commentStart;
        return commentStateToTokenType(state);
            }  // fall though
            case 245: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return TokenType.BAD_CHARACTER;
            } 
            // fall through
          case 119: break;
          case 2: 
            { return KtTokens.INTEGER_LITERAL;
            } 
            // fall through
          case 120: break;
          case 3: 
            { return KtTokens.IDENTIFIER;
            } 
            // fall through
          case 121: break;
          case 4: 
            { return KtTokens.WHITE_SPACE;
            } 
            // fall through
          case 122: break;
          case 5: 
            { pushState(UNMATCHED_BACKTICK); return TokenType.BAD_CHARACTER;
            } 
            // fall through
          case 123: break;
          case 6: 
            { return KtTokens.DIV       ;
            } 
            // fall through
          case 124: break;
          case 7: 
            { return KtTokens.HASH      ;
            } 
            // fall through
          case 125: break;
          case 8: 
            { return KtTokens.EXCL      ;
            } 
            // fall through
          case 126: break;
          case 9: 
            { return KtTokens.DOT       ;
            } 
            // fall through
          case 127: break;
          case 10: 
            { return KtTokens.MINUS     ;
            } 
            // fall through
          case 128: break;
          case 11: 
            { return KtTokens.CHARACTER_LITERAL;
            } 
            // fall through
          case 129: break;
          case 12: 
            { pushState(STRING); return KtTokens.OPEN_QUOTE;
            } 
            // fall through
          case 130: break;
          case 13: 
            { return KtTokens.LBRACE    ;
            } 
            // fall through
          case 131: break;
          case 14: 
            { return KtTokens.RBRACE    ;
            } 
            // fall through
          case 132: break;
          case 15: 
            { return KtTokens.MUL       ;
            } 
            // fall through
          case 133: break;
          case 16: 
            { return KtTokens.EQ        ;
            } 
            // fall through
          case 134: break;
          case 17: 
            { return KtTokens.QUEST     ;
            } 
            // fall through
          case 135: break;
          case 18: 
            { return KtTokens.PLUS      ;
            } 
            // fall through
          case 136: break;
          case 19: 
            { ltCount++; return KtTokens.LT        ;
            } 
            // fall through
          case 137: break;
          case 20: 
            { if(ltCount > 0) {
              ltCount--;
          }
          return KtTokens.GT;
            } 
            // fall through
          case 138: break;
          case 21: 
            { return KtTokens.AMP       ;
            } 
            // fall through
          case 139: break;
          case 22: 
            { return KtTokens.PIPE      ;
            } 
            // fall through
          case 140: break;
          case 23: 
            { return KtTokens.CARET     ;
            } 
            // fall through
          case 141: break;
          case 24: 
            { return KtTokens.PERC      ;
            } 
            // fall through
          case 142: break;
          case 25: 
            { return KtTokens.COLON     ;
            } 
            // fall through
          case 143: break;
          case 26: 
            { return KtTokens.LBRACKET  ;
            } 
            // fall through
          case 144: break;
          case 27: 
            { return KtTokens.RBRACKET  ;
            } 
            // fall through
          case 145: break;
          case 28: 
            { return KtTokens.LPAR      ;
            } 
            // fall through
          case 146: break;
          case 29: 
            { return KtTokens.RPAR      ;
            } 
            // fall through
          case 147: break;
          case 30: 
            { return KtTokens.TILDE     ;
            } 
            // fall through
          case 148: break;
          case 31: 
            { return KtTokens.SEMICOLON ;
            } 
            // fall through
          case 149: break;
          case 32: 
            { return KtTokens.COMMA     ;
            } 
            // fall through
          case 150: break;
          case 33: 
            { return KtTokens.AT        ;
            } 
            // fall through
          case 151: break;
          case 34: 
            { return KtTokens.REGULAR_STRING_PART;
            } 
            // fall through
          case 152: break;
          case 35: 
            { popState(); yypushback(1); return KtTokens.DANGLING_NEWLINE;
            } 
            // fall through
          case 153: break;
          case 36: 
            { popState(); return KtTokens.CLOSING_QUOTE;
            } 
            // fall through
          case 154: break;
          case 37: 
            { popState(); return KtTokens.IDENTIFIER;
            } 
            // fall through
          case 155: break;
          case 38: 
            { 
            } 
            // fall through
          case 156: break;
          case 39: 
            { lBraceCount++; return KtTokens.LBRACE;
            } 
            // fall through
          case 157: break;
          case 40: 
            { if (lBraceCount == 0) {
                                             popState();
                                             return KtTokens.LONG_TEMPLATE_ENTRY_END;
                                           }
                                           lBraceCount--;
                                           return KtTokens.RBRACE;
            } 
            // fall through
          case 158: break;
          case 41: 
            { return KtTokens.FLOAT_LITERAL;
            } 
            // fall through
          case 159: break;
          case 42: 
            { return KtTokens.FIELD_IDENTIFIER;
            } 
            // fall through
          case 160: break;
          case 43: 
            { return KtTokens.EOL_COMMENT;
            } 
            // fall through
          case 161: break;
          case 44: 
            { pushState(BLOCK_COMMENT);
    commentDepth = 0;
    commentStart = getTokenStart();
            } 
            // fall through
          case 162: break;
          case 45: 
            { return KtTokens.DIVEQ     ;
            } 
            // fall through
          case 163: break;
          case 46: 
            { if (zzCurrentPos == 0) {
                return KtTokens.SHEBANG_COMMENT;
            }
            else {
                yypushback(yylength() - 1);
                return KtTokens.HASH;
            }
            } 
            // fall through
          case 164: break;
          case 47: 
            { return KtTokens.EXCLEQ    ;
            } 
            // fall through
          case 165: break;
          case 48: 
            { return KtTokens.RANGE     ;
            } 
            // fall through
          case 166: break;
          case 49: 
            { return KtTokens.MINUSMINUS;
            } 
            // fall through
          case 167: break;
          case 50: 
            { return KtTokens.MINUSEQ   ;
            } 
            // fall through
          case 168: break;
          case 51: 
            { return KtTokens.ARROW     ;
            } 
            // fall through
          case 169: break;
          case 52: 
            { return KtTokens.IS_KEYWORD ;
            } 
            // fall through
          case 170: break;
          case 53: 
            { return KtTokens.IN_KEYWORD ;
            } 
            // fall through
          case 171: break;
          case 54: 
            { return KtTokens.IF_KEYWORD ;
            } 
            // fall through
          case 172: break;
          case 55: 
            { return KtTokens.MULTEQ    ;
            } 
            // fall through
          case 173: break;
          case 56: 
            { return KtTokens.AS_KEYWORD ;
            } 
            // fall through
          case 174: break;
          case 57: 
            { return KtTokens.DO_KEYWORD ;
            } 
            // fall through
          case 175: break;
          case 58: 
            { return KtTokens.EQEQ      ;
            } 
            // fall through
          case 176: break;
          case 59: 
            { return KtTokens.DOUBLE_ARROW;
            } 
            // fall through
          case 177: break;
          case 60: 
            { return KtTokens.PLUSEQ    ;
            } 
            // fall through
          case 178: break;
          case 61: 
            { return KtTokens.PLUSPLUS  ;
            } 
            // fall through
          case 179: break;
          case 62: 
            { return KtTokens.LTEQ      ;
            } 
            // fall through
          case 180: break;
          case 63: 
            { return KtTokens.LTLT      ;
            } 
            // fall through
          case 181: break;
          case 64: 
            { return KtTokens.GTEQ      ;
            } 
            // fall through
          case 182: break;
          case 65: 
            { if(ltCount >= 2) {
              ltCount--;
              yypushback(1);
              return KtTokens.GT;
          } else {
              return KtTokens.GTGT;

          }
            } 
            // fall through
          case 183: break;
          case 66: 
            { return KtTokens.AMPEQ     ;
            } 
            // fall through
          case 184: break;
          case 67: 
            { return KtTokens.ANDAND    ;
            } 
            // fall through
          case 185: break;
          case 68: 
            { return KtTokens.PIPEEQ    ;
            } 
            // fall through
          case 186: break;
          case 69: 
            { return KtTokens.OROR      ;
            } 
            // fall through
          case 187: break;
          case 70: 
            { return KtTokens.CARETEQ   ;
            } 
            // fall through
          case 188: break;
          case 71: 
            { return KtTokens.PERCEQ    ;
            } 
            // fall through
          case 189: break;
          case 72: 
            { return KtTokens.COLONCOLON;
            } 
            // fall through
          case 190: break;
          case 73: 
            { return KtTokens.DOUBLE_SEMICOLON;
            } 
            // fall through
          case 191: break;
          case 74: 
            { pushState(SHORT_TEMPLATE_ENTRY);
                                                        yypushback(yylength() - 1);
                                                        return KtTokens.SHORT_TEMPLATE_ENTRY_START;
            } 
            // fall through
          case 192: break;
          case 75: 
            { pushState(LONG_TEMPLATE_ENTRY); return KtTokens.LONG_TEMPLATE_ENTRY_START;
            } 
            // fall through
          case 193: break;
          case 76: 
            { return KtTokens.ESCAPE_SEQUENCE;
            } 
            // fall through
          case 194: break;
          case 77: 
            { commentDepth++;
            } 
            // fall through
          case 195: break;
          case 78: 
            { if (commentDepth > 0) {
            commentDepth--;
        }
        else {
             int state = yystate();
             popState();
             zzStartRead = commentStart;
             return commentStateToTokenType(state);
        }
            } 
            // fall through
          case 196: break;
          case 79: 
            { yypushback(2); return KtTokens.INTEGER_LITERAL;
            } 
            // fall through
          case 197: break;
          case 80: 
            { pushState(DOC_COMMENT);
    commentDepth = 0;
    commentStart = getTokenStart();
            } 
            // fall through
          case 198: break;
          case 81: 
            { return KtTokens.NOT_IS;
            } 
            // fall through
          case 199: break;
          case 82: 
            { return KtTokens.NOT_IN;
            } 
            // fall through
          case 200: break;
          case 83: 
            { return KtTokens.EXCLEQEQEQ;
            } 
            // fall through
          case 201: break;
          case 84: 
            { return KtTokens.RESERVED  ;
            } 
            // fall through
          case 202: break;
          case 85: 
            { pushState(RAW_STRING); return KtTokens.OPEN_QUOTE;
            } 
            // fall through
          case 203: break;
          case 86: 
            { return KtTokens.TRY_KEYWORD ;
            } 
            // fall through
          case 204: break;
          case 87: 
            { return KtTokens.AS_SAFE;
            } 
            // fall through
          case 205: break;
          case 88: 
            { return KtTokens.FUN_KEYWORD ;
            } 
            // fall through
          case 206: break;
          case 89: 
            { return KtTokens.FOR_KEYWORD ;
            } 
            // fall through
          case 207: break;
          case 90: 
            { return KtTokens.VAL_KEYWORD ;
            } 
            // fall through
          case 208: break;
          case 91: 
            { return KtTokens.VAR_KEYWORD ;
            } 
            // fall through
          case 209: break;
          case 92: 
            { return KtTokens.EQEQEQ    ;
            } 
            // fall through
          case 210: break;
          case 93: 
            { return KtTokens.LTLTEQ    ;
            } 
            // fall through
          case 211: break;
          case 94: 
            { return KtTokens.GTGTEQ    ;
            } 
            // fall through
          case 212: break;
          case 95: 
            { if(ltCount >= 3) {
              ltCount--;
              yypushback(2);
              return KtTokens.GT;
          } else {
              return KtTokens.GTGTGT;
          }
            } 
            // fall through
          case 213: break;
          case 96: 
            { int length = yytext().length();
                                    if (length <= 3) { // closing """
                                        popState();
                                        return KtTokens.CLOSING_QUOTE;
                                    }
                                    else { // some quotes at the end of a string, e.g. """ "foo""""
                                        yypushback(3); // return the closing quotes (""") to the stream
                                        return KtTokens.REGULAR_STRING_PART;
                                    }
            } 
            // fall through
          case 214: break;
          case 97: 
            { return KtTokens.BLOCK_COMMENT;
            } 
            // fall through
          case 215: break;
          case 98: 
            { yypushback(3); return KtTokens.EXCL;
            } 
            // fall through
          case 216: break;
          case 99: 
            { return KtTokens.THIS_KEYWORD ;
            } 
            // fall through
          case 217: break;
          case 100: 
            { return KtTokens.TRUE_KEYWORD ;
            } 
            // fall through
          case 218: break;
          case 101: 
            { return KtTokens.ELSE_KEYWORD ;
            } 
            // fall through
          case 219: break;
          case 102: 
            { return KtTokens.NULL_KEYWORD ;
            } 
            // fall through
          case 220: break;
          case 103: 
            { return KtTokens.WHEN_KEYWORD ;
            } 
            // fall through
          case 221: break;
          case 104: 
            { return KtTokens.GTGTGTEQ  ;
            } 
            // fall through
          case 222: break;
          case 105: 
            { popState(); return KtTokens.THIS_KEYWORD;
            } 
            // fall through
          case 223: break;
          case 106: 
            { return KtTokens.THROW_KEYWORD ;
            } 
            // fall through
          case 224: break;
          case 107: 
            { return KtTokens.SUPER_KEYWORD ;
            } 
            // fall through
          case 225: break;
          case 108: 
            { return KtTokens.FALSE_KEYWORD ;
            } 
            // fall through
          case 226: break;
          case 109: 
            { return KtTokens.CLASS_KEYWORD ;
            } 
            // fall through
          case 227: break;
          case 110: 
            { return KtTokens.BREAK_KEYWORD ;
            } 
            // fall through
          case 228: break;
          case 111: 
            { return KtTokens.WHILE_KEYWORD ;
            } 
            // fall through
          case 229: break;
          case 112: 
            { return KtTokens.TYPEOF_KEYWORD ;
            } 
            // fall through
          case 230: break;
          case 113: 
            { return KtTokens.RETURN_KEYWORD ;
            } 
            // fall through
          case 231: break;
          case 114: 
            { return KtTokens.OBJECT_KEYWORD ;
            } 
            // fall through
          case 232: break;
          case 115: 
            { return KtTokens.PACKAGE_KEYWORD ;
            } 
            // fall through
          case 233: break;
          case 116: 
            { return KtTokens.CONTINUE_KEYWORD ;
            } 
            // fall through
          case 234: break;
          case 117: 
            { return KtTokens.TYPE_ALIAS_KEYWORD ;
            } 
            // fall through
          case 235: break;
          case 118: 
            { return KtTokens.INTERFACE_KEYWORD ;
            } 
            // fall through
          case 236: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
